apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geocentric-model-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Sir-gits-a-lot/all-hands-argo
    targetRevision: HEAD
    path: ./declarative/manifests/heliocentric-model
   
  destination:
    server: https://kubernetes.default.svc
    namespace: heliocentric-model

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true