apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://172.18.0.6:32569
  template:
    metadata:
      name: '{{cluster}}-app'
    spec:
      project: default
      source:
        repoURL: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/manifest-repo
        targetRevision: HEAD
        path: ./helm-chart-{{cluster}}
      destination:
        server: '{{url}}'
        namespace: random-shapes
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true